import {
  LayoutDashboard,
  Users,
  List,
  Sprout,
  Store,
  Briefcase,
  Warehouse,
  Truck,
  PackageOpen,
  Boxes,
  Layers,
  IndianRupee,
  Receipt,
  BookOpen,
  Calendar,
  Package,
  Handshake,
  FileText,
  Ticket,
  BarChart3,
  ClipboardList,
  TrendingUp,
  UserCheck,
  Settings,
  Home,
  Menu,
  Circle,
  UserPlus,
  Search,
  DoorOpen,
  ArrowRightLeft,
  Percent,
  Banknote,
  Database,
  Wheat,
  MapPin,
  Building2,
  HardHat,
  HelpCircle,
  Plus,
  ChevronDown,
  FileStack,
  CreditCard,
  type LucideIcon,
} from "lucide-react"

// Static icon map to avoid creating components during render
export const iconMap: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  "users": Users,
  "list": List,
  "sprout": Sprout,
  "store": Store,
  "briefcase": Briefcase,
  "warehouse": Warehouse,
  "truck": Truck,
  "package-open": PackageOpen,
  "boxes": Boxes,
  "layers": Layers,
  "indian-rupee": IndianRupee,
  "receipt": Receipt,
  "book-open": BookOpen,
  "calendar": Calendar,
  "package": Package,
  "handshake": Handshake,
  "file-text": FileText,
  "ticket": Ticket,
  "file-invoice": FileText, // Using FileText as fallback
  "bar-chart-3": BarChart3,
  "clipboard-list": ClipboardList,
  "trending-up": TrendingUp,
  "user-check": UserCheck,
  "settings": Settings,
  "home": Home,
  "menu": Menu,
  "user-plus": UserPlus,
  "search": Search,
  "door-open": DoorOpen,
  "arrow-right-left": ArrowRightLeft,
  "percent": Percent,
  "banknote": Banknote,
  "database": Database,
  "wheat": Wheat,
  "map-pin": MapPin,
  "building-2": Building2,
  "hard-hat": HardHat,
  "help-circle": HelpCircle,
  "plus": Plus,
  "chevron-down": ChevronDown,
  "file-stack": FileStack,
  "credit-card": CreditCard,
}

export function getIcon(iconName: string): LucideIcon {
  return iconMap[iconName] || Circle
}
