/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfirmSignupRouteImport } from './routes/confirm-signup'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMastersRouteImport } from './routes/_authenticated/masters'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTradingIndexRouteImport } from './routes/_authenticated/trading/index'
import { Route as AuthenticatedPayrollIndexRouteImport } from './routes/_authenticated/payroll/index'
import { Route as AuthenticatedLoansIndexRouteImport } from './routes/_authenticated/loans/index'
import { Route as AuthenticatedBillingIndexRouteImport } from './routes/_authenticated/billing/index'
import { Route as AuthenticatedBardanaIndexRouteImport } from './routes/_authenticated/bardana/index'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts/index'
import { Route as AuthenticatedWarehouseUnloadingRouteImport } from './routes/_authenticated/warehouse/unloading'
import { Route as AuthenticatedWarehouseTemperatureRouteImport } from './routes/_authenticated/warehouse/temperature'
import { Route as AuthenticatedWarehouseShiftingRouteImport } from './routes/_authenticated/warehouse/shifting'
import { Route as AuthenticatedWarehouseRoomMapRouteImport } from './routes/_authenticated/warehouse/room-map'
import { Route as AuthenticatedWarehouseMeterReadingRouteImport } from './routes/_authenticated/warehouse/meter-reading'
import { Route as AuthenticatedWarehouseLoadingRouteImport } from './routes/_authenticated/warehouse/loading'
import { Route as AuthenticatedWarehouseChambersRouteImport } from './routes/_authenticated/warehouse/chambers'
import { Route as AuthenticatedTradingSaudaRouteImport } from './routes/_authenticated/trading/sauda'
import { Route as AuthenticatedTradingKataiRouteImport } from './routes/_authenticated/trading/katai'
import { Route as AuthenticatedTradingGatePassRouteImport } from './routes/_authenticated/trading/gate-pass'
import { Route as AuthenticatedPayrollSalaryRouteImport } from './routes/_authenticated/payroll/salary'
import { Route as AuthenticatedPayrollPayslipRouteImport } from './routes/_authenticated/payroll/payslip'
import { Route as AuthenticatedPayrollMastersRouteImport } from './routes/_authenticated/payroll/masters'
import { Route as AuthenticatedPayrollLoansRouteImport } from './routes/_authenticated/payroll/loans'
import { Route as AuthenticatedPayrollEmployeesRouteImport } from './routes/_authenticated/payroll/employees'
import { Route as AuthenticatedPayrollDailyWagesRouteImport } from './routes/_authenticated/payroll/daily-wages'
import { Route as AuthenticatedPayrollAttendanceRouteImport } from './routes/_authenticated/payroll/attendance'
import { Route as AuthenticatedLoansLoansRouteImport } from './routes/_authenticated/loans/loans'
import { Route as AuthenticatedLoansLedgerRouteImport } from './routes/_authenticated/loans/ledger'
import { Route as AuthenticatedLoansInterestChartRouteImport } from './routes/_authenticated/loans/interest-chart'
import { Route as AuthenticatedLoansAdvancesRouteImport } from './routes/_authenticated/loans/advances'
import { Route as AuthenticatedInventoryTakpattiRouteImport } from './routes/_authenticated/inventory/takpatti'
import { Route as AuthenticatedInventoryStockTransferRouteImport } from './routes/_authenticated/inventory/stock-transfer'
import { Route as AuthenticatedInventoryNikasiRouteImport } from './routes/_authenticated/inventory/nikasi'
import { Route as AuthenticatedInventoryAmadRouteImport } from './routes/_authenticated/inventory/amad'
import { Route as AuthenticatedBillingRentBillsRouteImport } from './routes/_authenticated/billing/rent-bills'
import { Route as AuthenticatedBillingReceiptsRouteImport } from './routes/_authenticated/billing/receipts'
import { Route as AuthenticatedBillingNewBillRouteImport } from './routes/_authenticated/billing/new-bill'
import { Route as AuthenticatedBillingBillIdRouteImport } from './routes/_authenticated/billing/$billId'
import { Route as AuthenticatedBardanaTypesRouteImport } from './routes/_authenticated/bardana/types'
import { Route as AuthenticatedBardanaReceiptsRouteImport } from './routes/_authenticated/bardana/receipts'
import { Route as AuthenticatedBardanaOutstandingRouteImport } from './routes/_authenticated/bardana/outstanding'
import { Route as AuthenticatedBardanaIssuesRouteImport } from './routes/_authenticated/bardana/issues'
import { Route as AuthenticatedAccountsVouchersRouteImport } from './routes/_authenticated/accounts/vouchers'
import { Route as AuthenticatedAccountsPartyLedgerRouteImport } from './routes/_authenticated/accounts/party-ledger'
import { Route as AuthenticatedAccountsInterestRouteImport } from './routes/_authenticated/accounts/interest'
import { Route as AuthenticatedAccountsDaybookRouteImport } from './routes/_authenticated/accounts/daybook'
import { Route as AuthenticatedAccountsChartOfAccountsRouteImport } from './routes/_authenticated/accounts/chart-of-accounts'
import { Route as AuthenticatedInventoryAmadAmadIdRouteImport } from './routes/_authenticated/inventory/amad.$amadId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmSignupRoute = ConfirmSignupRouteImport.update({
  id: '/confirm-signup',
  path: '/confirm-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMastersRoute = AuthenticatedMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradingIndexRoute =
  AuthenticatedTradingIndexRouteImport.update({
    id: '/trading/',
    path: '/trading/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayrollIndexRoute =
  AuthenticatedPayrollIndexRouteImport.update({
    id: '/payroll/',
    path: '/payroll/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoansIndexRoute = AuthenticatedLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingIndexRoute =
  AuthenticatedBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBardanaIndexRoute =
  AuthenticatedBardanaIndexRouteImport.update({
    id: '/bardana/',
    path: '/bardana/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWarehouseUnloadingRoute =
  AuthenticatedWarehouseUnloadingRouteImport.update({
    id: '/warehouse/unloading',
    path: '/warehouse/unloading',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWarehouseTemperatureRoute =
  AuthenticatedWarehouseTemperatureRouteImport.update({
    id: '/warehouse/temperature',
    path: '/warehouse/temperature',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWarehouseShiftingRoute =
  AuthenticatedWarehouseShiftingRouteImport.update({
    id: '/warehouse/shifting',
    path: '/warehouse/shifting',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWarehouseRoomMapRoute =
  AuthenticatedWarehouseRoomMapRouteImport.update({
    id: '/warehouse/room-map',
    path: '/warehouse/room-map',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWarehouseMeterReadingRoute =
  AuthenticatedWarehouseMeterReadingRouteImport.update({
    id: '/warehouse/meter-reading',
    path: '/warehouse/meter-reading',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWarehouseLoadingRoute =
  AuthenticatedWarehouseLoadingRouteImport.update({
    id: '/warehouse/loading',
    path: '/warehouse/loading',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWarehouseChambersRoute =
  AuthenticatedWarehouseChambersRouteImport.update({
    id: '/warehouse/chambers',
    path: '/warehouse/chambers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTradingSaudaRoute =
  AuthenticatedTradingSaudaRouteImport.update({
    id: '/trading/sauda',
    path: '/trading/sauda',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTradingKataiRoute =
  AuthenticatedTradingKataiRouteImport.update({
    id: '/trading/katai',
    path: '/trading/katai',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTradingGatePassRoute =
  AuthenticatedTradingGatePassRouteImport.update({
    id: '/trading/gate-pass',
    path: '/trading/gate-pass',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayrollSalaryRoute =
  AuthenticatedPayrollSalaryRouteImport.update({
    id: '/payroll/salary',
    path: '/payroll/salary',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayrollPayslipRoute =
  AuthenticatedPayrollPayslipRouteImport.update({
    id: '/payroll/payslip',
    path: '/payroll/payslip',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayrollMastersRoute =
  AuthenticatedPayrollMastersRouteImport.update({
    id: '/payroll/masters',
    path: '/payroll/masters',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayrollLoansRoute =
  AuthenticatedPayrollLoansRouteImport.update({
    id: '/payroll/loans',
    path: '/payroll/loans',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayrollEmployeesRoute =
  AuthenticatedPayrollEmployeesRouteImport.update({
    id: '/payroll/employees',
    path: '/payroll/employees',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayrollDailyWagesRoute =
  AuthenticatedPayrollDailyWagesRouteImport.update({
    id: '/payroll/daily-wages',
    path: '/payroll/daily-wages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayrollAttendanceRoute =
  AuthenticatedPayrollAttendanceRouteImport.update({
    id: '/payroll/attendance',
    path: '/payroll/attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoansLoansRoute = AuthenticatedLoansLoansRouteImport.update({
  id: '/loans/loans',
  path: '/loans/loans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoansLedgerRoute =
  AuthenticatedLoansLedgerRouteImport.update({
    id: '/loans/ledger',
    path: '/loans/ledger',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoansInterestChartRoute =
  AuthenticatedLoansInterestChartRouteImport.update({
    id: '/loans/interest-chart',
    path: '/loans/interest-chart',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoansAdvancesRoute =
  AuthenticatedLoansAdvancesRouteImport.update({
    id: '/loans/advances',
    path: '/loans/advances',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryTakpattiRoute =
  AuthenticatedInventoryTakpattiRouteImport.update({
    id: '/inventory/takpatti',
    path: '/inventory/takpatti',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryStockTransferRoute =
  AuthenticatedInventoryStockTransferRouteImport.update({
    id: '/inventory/stock-transfer',
    path: '/inventory/stock-transfer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryNikasiRoute =
  AuthenticatedInventoryNikasiRouteImport.update({
    id: '/inventory/nikasi',
    path: '/inventory/nikasi',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryAmadRoute =
  AuthenticatedInventoryAmadRouteImport.update({
    id: '/inventory/amad',
    path: '/inventory/amad',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingRentBillsRoute =
  AuthenticatedBillingRentBillsRouteImport.update({
    id: '/billing/rent-bills',
    path: '/billing/rent-bills',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingReceiptsRoute =
  AuthenticatedBillingReceiptsRouteImport.update({
    id: '/billing/receipts',
    path: '/billing/receipts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingNewBillRoute =
  AuthenticatedBillingNewBillRouteImport.update({
    id: '/billing/new-bill',
    path: '/billing/new-bill',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingBillIdRoute =
  AuthenticatedBillingBillIdRouteImport.update({
    id: '/billing/$billId',
    path: '/billing/$billId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBardanaTypesRoute =
  AuthenticatedBardanaTypesRouteImport.update({
    id: '/bardana/types',
    path: '/bardana/types',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBardanaReceiptsRoute =
  AuthenticatedBardanaReceiptsRouteImport.update({
    id: '/bardana/receipts',
    path: '/bardana/receipts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBardanaOutstandingRoute =
  AuthenticatedBardanaOutstandingRouteImport.update({
    id: '/bardana/outstanding',
    path: '/bardana/outstanding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBardanaIssuesRoute =
  AuthenticatedBardanaIssuesRouteImport.update({
    id: '/bardana/issues',
    path: '/bardana/issues',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsVouchersRoute =
  AuthenticatedAccountsVouchersRouteImport.update({
    id: '/accounts/vouchers',
    path: '/accounts/vouchers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsPartyLedgerRoute =
  AuthenticatedAccountsPartyLedgerRouteImport.update({
    id: '/accounts/party-ledger',
    path: '/accounts/party-ledger',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsInterestRoute =
  AuthenticatedAccountsInterestRouteImport.update({
    id: '/accounts/interest',
    path: '/accounts/interest',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsDaybookRoute =
  AuthenticatedAccountsDaybookRouteImport.update({
    id: '/accounts/daybook',
    path: '/accounts/daybook',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsChartOfAccountsRoute =
  AuthenticatedAccountsChartOfAccountsRouteImport.update({
    id: '/accounts/chart-of-accounts',
    path: '/accounts/chart-of-accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryAmadAmadIdRoute =
  AuthenticatedInventoryAmadAmadIdRouteImport.update({
    id: '/$amadId',
    path: '/$amadId',
    getParentRoute: () => AuthenticatedInventoryAmadRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm-signup': typeof ConfirmSignupRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/masters': typeof AuthenticatedMastersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/accounts/chart-of-accounts': typeof AuthenticatedAccountsChartOfAccountsRoute
  '/accounts/daybook': typeof AuthenticatedAccountsDaybookRoute
  '/accounts/interest': typeof AuthenticatedAccountsInterestRoute
  '/accounts/party-ledger': typeof AuthenticatedAccountsPartyLedgerRoute
  '/accounts/vouchers': typeof AuthenticatedAccountsVouchersRoute
  '/bardana/issues': typeof AuthenticatedBardanaIssuesRoute
  '/bardana/outstanding': typeof AuthenticatedBardanaOutstandingRoute
  '/bardana/receipts': typeof AuthenticatedBardanaReceiptsRoute
  '/bardana/types': typeof AuthenticatedBardanaTypesRoute
  '/billing/$billId': typeof AuthenticatedBillingBillIdRoute
  '/billing/new-bill': typeof AuthenticatedBillingNewBillRoute
  '/billing/receipts': typeof AuthenticatedBillingReceiptsRoute
  '/billing/rent-bills': typeof AuthenticatedBillingRentBillsRoute
  '/inventory/amad': typeof AuthenticatedInventoryAmadRouteWithChildren
  '/inventory/nikasi': typeof AuthenticatedInventoryNikasiRoute
  '/inventory/stock-transfer': typeof AuthenticatedInventoryStockTransferRoute
  '/inventory/takpatti': typeof AuthenticatedInventoryTakpattiRoute
  '/loans/advances': typeof AuthenticatedLoansAdvancesRoute
  '/loans/interest-chart': typeof AuthenticatedLoansInterestChartRoute
  '/loans/ledger': typeof AuthenticatedLoansLedgerRoute
  '/loans/loans': typeof AuthenticatedLoansLoansRoute
  '/payroll/attendance': typeof AuthenticatedPayrollAttendanceRoute
  '/payroll/daily-wages': typeof AuthenticatedPayrollDailyWagesRoute
  '/payroll/employees': typeof AuthenticatedPayrollEmployeesRoute
  '/payroll/loans': typeof AuthenticatedPayrollLoansRoute
  '/payroll/masters': typeof AuthenticatedPayrollMastersRoute
  '/payroll/payslip': typeof AuthenticatedPayrollPayslipRoute
  '/payroll/salary': typeof AuthenticatedPayrollSalaryRoute
  '/trading/gate-pass': typeof AuthenticatedTradingGatePassRoute
  '/trading/katai': typeof AuthenticatedTradingKataiRoute
  '/trading/sauda': typeof AuthenticatedTradingSaudaRoute
  '/warehouse/chambers': typeof AuthenticatedWarehouseChambersRoute
  '/warehouse/loading': typeof AuthenticatedWarehouseLoadingRoute
  '/warehouse/meter-reading': typeof AuthenticatedWarehouseMeterReadingRoute
  '/warehouse/room-map': typeof AuthenticatedWarehouseRoomMapRoute
  '/warehouse/shifting': typeof AuthenticatedWarehouseShiftingRoute
  '/warehouse/temperature': typeof AuthenticatedWarehouseTemperatureRoute
  '/warehouse/unloading': typeof AuthenticatedWarehouseUnloadingRoute
  '/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/bardana/': typeof AuthenticatedBardanaIndexRoute
  '/billing/': typeof AuthenticatedBillingIndexRoute
  '/loans/': typeof AuthenticatedLoansIndexRoute
  '/payroll/': typeof AuthenticatedPayrollIndexRoute
  '/trading/': typeof AuthenticatedTradingIndexRoute
  '/inventory/amad/$amadId': typeof AuthenticatedInventoryAmadAmadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-signup': typeof ConfirmSignupRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/masters': typeof AuthenticatedMastersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/accounts/chart-of-accounts': typeof AuthenticatedAccountsChartOfAccountsRoute
  '/accounts/daybook': typeof AuthenticatedAccountsDaybookRoute
  '/accounts/interest': typeof AuthenticatedAccountsInterestRoute
  '/accounts/party-ledger': typeof AuthenticatedAccountsPartyLedgerRoute
  '/accounts/vouchers': typeof AuthenticatedAccountsVouchersRoute
  '/bardana/issues': typeof AuthenticatedBardanaIssuesRoute
  '/bardana/outstanding': typeof AuthenticatedBardanaOutstandingRoute
  '/bardana/receipts': typeof AuthenticatedBardanaReceiptsRoute
  '/bardana/types': typeof AuthenticatedBardanaTypesRoute
  '/billing/$billId': typeof AuthenticatedBillingBillIdRoute
  '/billing/new-bill': typeof AuthenticatedBillingNewBillRoute
  '/billing/receipts': typeof AuthenticatedBillingReceiptsRoute
  '/billing/rent-bills': typeof AuthenticatedBillingRentBillsRoute
  '/inventory/amad': typeof AuthenticatedInventoryAmadRouteWithChildren
  '/inventory/nikasi': typeof AuthenticatedInventoryNikasiRoute
  '/inventory/stock-transfer': typeof AuthenticatedInventoryStockTransferRoute
  '/inventory/takpatti': typeof AuthenticatedInventoryTakpattiRoute
  '/loans/advances': typeof AuthenticatedLoansAdvancesRoute
  '/loans/interest-chart': typeof AuthenticatedLoansInterestChartRoute
  '/loans/ledger': typeof AuthenticatedLoansLedgerRoute
  '/loans/loans': typeof AuthenticatedLoansLoansRoute
  '/payroll/attendance': typeof AuthenticatedPayrollAttendanceRoute
  '/payroll/daily-wages': typeof AuthenticatedPayrollDailyWagesRoute
  '/payroll/employees': typeof AuthenticatedPayrollEmployeesRoute
  '/payroll/loans': typeof AuthenticatedPayrollLoansRoute
  '/payroll/masters': typeof AuthenticatedPayrollMastersRoute
  '/payroll/payslip': typeof AuthenticatedPayrollPayslipRoute
  '/payroll/salary': typeof AuthenticatedPayrollSalaryRoute
  '/trading/gate-pass': typeof AuthenticatedTradingGatePassRoute
  '/trading/katai': typeof AuthenticatedTradingKataiRoute
  '/trading/sauda': typeof AuthenticatedTradingSaudaRoute
  '/warehouse/chambers': typeof AuthenticatedWarehouseChambersRoute
  '/warehouse/loading': typeof AuthenticatedWarehouseLoadingRoute
  '/warehouse/meter-reading': typeof AuthenticatedWarehouseMeterReadingRoute
  '/warehouse/room-map': typeof AuthenticatedWarehouseRoomMapRoute
  '/warehouse/shifting': typeof AuthenticatedWarehouseShiftingRoute
  '/warehouse/temperature': typeof AuthenticatedWarehouseTemperatureRoute
  '/warehouse/unloading': typeof AuthenticatedWarehouseUnloadingRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
  '/bardana': typeof AuthenticatedBardanaIndexRoute
  '/billing': typeof AuthenticatedBillingIndexRoute
  '/loans': typeof AuthenticatedLoansIndexRoute
  '/payroll': typeof AuthenticatedPayrollIndexRoute
  '/trading': typeof AuthenticatedTradingIndexRoute
  '/inventory/amad/$amadId': typeof AuthenticatedInventoryAmadAmadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/confirm-signup': typeof ConfirmSignupRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/masters': typeof AuthenticatedMastersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/accounts/chart-of-accounts': typeof AuthenticatedAccountsChartOfAccountsRoute
  '/_authenticated/accounts/daybook': typeof AuthenticatedAccountsDaybookRoute
  '/_authenticated/accounts/interest': typeof AuthenticatedAccountsInterestRoute
  '/_authenticated/accounts/party-ledger': typeof AuthenticatedAccountsPartyLedgerRoute
  '/_authenticated/accounts/vouchers': typeof AuthenticatedAccountsVouchersRoute
  '/_authenticated/bardana/issues': typeof AuthenticatedBardanaIssuesRoute
  '/_authenticated/bardana/outstanding': typeof AuthenticatedBardanaOutstandingRoute
  '/_authenticated/bardana/receipts': typeof AuthenticatedBardanaReceiptsRoute
  '/_authenticated/bardana/types': typeof AuthenticatedBardanaTypesRoute
  '/_authenticated/billing/$billId': typeof AuthenticatedBillingBillIdRoute
  '/_authenticated/billing/new-bill': typeof AuthenticatedBillingNewBillRoute
  '/_authenticated/billing/receipts': typeof AuthenticatedBillingReceiptsRoute
  '/_authenticated/billing/rent-bills': typeof AuthenticatedBillingRentBillsRoute
  '/_authenticated/inventory/amad': typeof AuthenticatedInventoryAmadRouteWithChildren
  '/_authenticated/inventory/nikasi': typeof AuthenticatedInventoryNikasiRoute
  '/_authenticated/inventory/stock-transfer': typeof AuthenticatedInventoryStockTransferRoute
  '/_authenticated/inventory/takpatti': typeof AuthenticatedInventoryTakpattiRoute
  '/_authenticated/loans/advances': typeof AuthenticatedLoansAdvancesRoute
  '/_authenticated/loans/interest-chart': typeof AuthenticatedLoansInterestChartRoute
  '/_authenticated/loans/ledger': typeof AuthenticatedLoansLedgerRoute
  '/_authenticated/loans/loans': typeof AuthenticatedLoansLoansRoute
  '/_authenticated/payroll/attendance': typeof AuthenticatedPayrollAttendanceRoute
  '/_authenticated/payroll/daily-wages': typeof AuthenticatedPayrollDailyWagesRoute
  '/_authenticated/payroll/employees': typeof AuthenticatedPayrollEmployeesRoute
  '/_authenticated/payroll/loans': typeof AuthenticatedPayrollLoansRoute
  '/_authenticated/payroll/masters': typeof AuthenticatedPayrollMastersRoute
  '/_authenticated/payroll/payslip': typeof AuthenticatedPayrollPayslipRoute
  '/_authenticated/payroll/salary': typeof AuthenticatedPayrollSalaryRoute
  '/_authenticated/trading/gate-pass': typeof AuthenticatedTradingGatePassRoute
  '/_authenticated/trading/katai': typeof AuthenticatedTradingKataiRoute
  '/_authenticated/trading/sauda': typeof AuthenticatedTradingSaudaRoute
  '/_authenticated/warehouse/chambers': typeof AuthenticatedWarehouseChambersRoute
  '/_authenticated/warehouse/loading': typeof AuthenticatedWarehouseLoadingRoute
  '/_authenticated/warehouse/meter-reading': typeof AuthenticatedWarehouseMeterReadingRoute
  '/_authenticated/warehouse/room-map': typeof AuthenticatedWarehouseRoomMapRoute
  '/_authenticated/warehouse/shifting': typeof AuthenticatedWarehouseShiftingRoute
  '/_authenticated/warehouse/temperature': typeof AuthenticatedWarehouseTemperatureRoute
  '/_authenticated/warehouse/unloading': typeof AuthenticatedWarehouseUnloadingRoute
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/_authenticated/bardana/': typeof AuthenticatedBardanaIndexRoute
  '/_authenticated/billing/': typeof AuthenticatedBillingIndexRoute
  '/_authenticated/loans/': typeof AuthenticatedLoansIndexRoute
  '/_authenticated/payroll/': typeof AuthenticatedPayrollIndexRoute
  '/_authenticated/trading/': typeof AuthenticatedTradingIndexRoute
  '/_authenticated/inventory/amad/$amadId': typeof AuthenticatedInventoryAmadAmadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-signup'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/masters'
    | '/settings'
    | '/accounts/chart-of-accounts'
    | '/accounts/daybook'
    | '/accounts/interest'
    | '/accounts/party-ledger'
    | '/accounts/vouchers'
    | '/bardana/issues'
    | '/bardana/outstanding'
    | '/bardana/receipts'
    | '/bardana/types'
    | '/billing/$billId'
    | '/billing/new-bill'
    | '/billing/receipts'
    | '/billing/rent-bills'
    | '/inventory/amad'
    | '/inventory/nikasi'
    | '/inventory/stock-transfer'
    | '/inventory/takpatti'
    | '/loans/advances'
    | '/loans/interest-chart'
    | '/loans/ledger'
    | '/loans/loans'
    | '/payroll/attendance'
    | '/payroll/daily-wages'
    | '/payroll/employees'
    | '/payroll/loans'
    | '/payroll/masters'
    | '/payroll/payslip'
    | '/payroll/salary'
    | '/trading/gate-pass'
    | '/trading/katai'
    | '/trading/sauda'
    | '/warehouse/chambers'
    | '/warehouse/loading'
    | '/warehouse/meter-reading'
    | '/warehouse/room-map'
    | '/warehouse/shifting'
    | '/warehouse/temperature'
    | '/warehouse/unloading'
    | '/accounts/'
    | '/bardana/'
    | '/billing/'
    | '/loans/'
    | '/payroll/'
    | '/trading/'
    | '/inventory/amad/$amadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-signup'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/masters'
    | '/settings'
    | '/accounts/chart-of-accounts'
    | '/accounts/daybook'
    | '/accounts/interest'
    | '/accounts/party-ledger'
    | '/accounts/vouchers'
    | '/bardana/issues'
    | '/bardana/outstanding'
    | '/bardana/receipts'
    | '/bardana/types'
    | '/billing/$billId'
    | '/billing/new-bill'
    | '/billing/receipts'
    | '/billing/rent-bills'
    | '/inventory/amad'
    | '/inventory/nikasi'
    | '/inventory/stock-transfer'
    | '/inventory/takpatti'
    | '/loans/advances'
    | '/loans/interest-chart'
    | '/loans/ledger'
    | '/loans/loans'
    | '/payroll/attendance'
    | '/payroll/daily-wages'
    | '/payroll/employees'
    | '/payroll/loans'
    | '/payroll/masters'
    | '/payroll/payslip'
    | '/payroll/salary'
    | '/trading/gate-pass'
    | '/trading/katai'
    | '/trading/sauda'
    | '/warehouse/chambers'
    | '/warehouse/loading'
    | '/warehouse/meter-reading'
    | '/warehouse/room-map'
    | '/warehouse/shifting'
    | '/warehouse/temperature'
    | '/warehouse/unloading'
    | '/accounts'
    | '/bardana'
    | '/billing'
    | '/loans'
    | '/payroll'
    | '/trading'
    | '/inventory/amad/$amadId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/confirm-signup'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/masters'
    | '/_authenticated/settings'
    | '/_authenticated/accounts/chart-of-accounts'
    | '/_authenticated/accounts/daybook'
    | '/_authenticated/accounts/interest'
    | '/_authenticated/accounts/party-ledger'
    | '/_authenticated/accounts/vouchers'
    | '/_authenticated/bardana/issues'
    | '/_authenticated/bardana/outstanding'
    | '/_authenticated/bardana/receipts'
    | '/_authenticated/bardana/types'
    | '/_authenticated/billing/$billId'
    | '/_authenticated/billing/new-bill'
    | '/_authenticated/billing/receipts'
    | '/_authenticated/billing/rent-bills'
    | '/_authenticated/inventory/amad'
    | '/_authenticated/inventory/nikasi'
    | '/_authenticated/inventory/stock-transfer'
    | '/_authenticated/inventory/takpatti'
    | '/_authenticated/loans/advances'
    | '/_authenticated/loans/interest-chart'
    | '/_authenticated/loans/ledger'
    | '/_authenticated/loans/loans'
    | '/_authenticated/payroll/attendance'
    | '/_authenticated/payroll/daily-wages'
    | '/_authenticated/payroll/employees'
    | '/_authenticated/payroll/loans'
    | '/_authenticated/payroll/masters'
    | '/_authenticated/payroll/payslip'
    | '/_authenticated/payroll/salary'
    | '/_authenticated/trading/gate-pass'
    | '/_authenticated/trading/katai'
    | '/_authenticated/trading/sauda'
    | '/_authenticated/warehouse/chambers'
    | '/_authenticated/warehouse/loading'
    | '/_authenticated/warehouse/meter-reading'
    | '/_authenticated/warehouse/room-map'
    | '/_authenticated/warehouse/shifting'
    | '/_authenticated/warehouse/temperature'
    | '/_authenticated/warehouse/unloading'
    | '/_authenticated/accounts/'
    | '/_authenticated/bardana/'
    | '/_authenticated/billing/'
    | '/_authenticated/loans/'
    | '/_authenticated/payroll/'
    | '/_authenticated/trading/'
    | '/_authenticated/inventory/amad/$amadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConfirmSignupRoute: typeof ConfirmSignupRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-signup': {
      id: '/confirm-signup'
      path: '/confirm-signup'
      fullPath: '/confirm-signup'
      preLoaderRoute: typeof ConfirmSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters': {
      id: '/_authenticated/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof AuthenticatedMastersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trading/': {
      id: '/_authenticated/trading/'
      path: '/trading'
      fullPath: '/trading/'
      preLoaderRoute: typeof AuthenticatedTradingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll/': {
      id: '/_authenticated/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof AuthenticatedPayrollIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loans/': {
      id: '/_authenticated/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof AuthenticatedLoansIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/': {
      id: '/_authenticated/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthenticatedBillingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bardana/': {
      id: '/_authenticated/bardana/'
      path: '/bardana'
      fullPath: '/bardana/'
      preLoaderRoute: typeof AuthenticatedBardanaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/warehouse/unloading': {
      id: '/_authenticated/warehouse/unloading'
      path: '/warehouse/unloading'
      fullPath: '/warehouse/unloading'
      preLoaderRoute: typeof AuthenticatedWarehouseUnloadingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/warehouse/temperature': {
      id: '/_authenticated/warehouse/temperature'
      path: '/warehouse/temperature'
      fullPath: '/warehouse/temperature'
      preLoaderRoute: typeof AuthenticatedWarehouseTemperatureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/warehouse/shifting': {
      id: '/_authenticated/warehouse/shifting'
      path: '/warehouse/shifting'
      fullPath: '/warehouse/shifting'
      preLoaderRoute: typeof AuthenticatedWarehouseShiftingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/warehouse/room-map': {
      id: '/_authenticated/warehouse/room-map'
      path: '/warehouse/room-map'
      fullPath: '/warehouse/room-map'
      preLoaderRoute: typeof AuthenticatedWarehouseRoomMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/warehouse/meter-reading': {
      id: '/_authenticated/warehouse/meter-reading'
      path: '/warehouse/meter-reading'
      fullPath: '/warehouse/meter-reading'
      preLoaderRoute: typeof AuthenticatedWarehouseMeterReadingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/warehouse/loading': {
      id: '/_authenticated/warehouse/loading'
      path: '/warehouse/loading'
      fullPath: '/warehouse/loading'
      preLoaderRoute: typeof AuthenticatedWarehouseLoadingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/warehouse/chambers': {
      id: '/_authenticated/warehouse/chambers'
      path: '/warehouse/chambers'
      fullPath: '/warehouse/chambers'
      preLoaderRoute: typeof AuthenticatedWarehouseChambersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trading/sauda': {
      id: '/_authenticated/trading/sauda'
      path: '/trading/sauda'
      fullPath: '/trading/sauda'
      preLoaderRoute: typeof AuthenticatedTradingSaudaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trading/katai': {
      id: '/_authenticated/trading/katai'
      path: '/trading/katai'
      fullPath: '/trading/katai'
      preLoaderRoute: typeof AuthenticatedTradingKataiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trading/gate-pass': {
      id: '/_authenticated/trading/gate-pass'
      path: '/trading/gate-pass'
      fullPath: '/trading/gate-pass'
      preLoaderRoute: typeof AuthenticatedTradingGatePassRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll/salary': {
      id: '/_authenticated/payroll/salary'
      path: '/payroll/salary'
      fullPath: '/payroll/salary'
      preLoaderRoute: typeof AuthenticatedPayrollSalaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll/payslip': {
      id: '/_authenticated/payroll/payslip'
      path: '/payroll/payslip'
      fullPath: '/payroll/payslip'
      preLoaderRoute: typeof AuthenticatedPayrollPayslipRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll/masters': {
      id: '/_authenticated/payroll/masters'
      path: '/payroll/masters'
      fullPath: '/payroll/masters'
      preLoaderRoute: typeof AuthenticatedPayrollMastersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll/loans': {
      id: '/_authenticated/payroll/loans'
      path: '/payroll/loans'
      fullPath: '/payroll/loans'
      preLoaderRoute: typeof AuthenticatedPayrollLoansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll/employees': {
      id: '/_authenticated/payroll/employees'
      path: '/payroll/employees'
      fullPath: '/payroll/employees'
      preLoaderRoute: typeof AuthenticatedPayrollEmployeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll/daily-wages': {
      id: '/_authenticated/payroll/daily-wages'
      path: '/payroll/daily-wages'
      fullPath: '/payroll/daily-wages'
      preLoaderRoute: typeof AuthenticatedPayrollDailyWagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll/attendance': {
      id: '/_authenticated/payroll/attendance'
      path: '/payroll/attendance'
      fullPath: '/payroll/attendance'
      preLoaderRoute: typeof AuthenticatedPayrollAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loans/loans': {
      id: '/_authenticated/loans/loans'
      path: '/loans/loans'
      fullPath: '/loans/loans'
      preLoaderRoute: typeof AuthenticatedLoansLoansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loans/ledger': {
      id: '/_authenticated/loans/ledger'
      path: '/loans/ledger'
      fullPath: '/loans/ledger'
      preLoaderRoute: typeof AuthenticatedLoansLedgerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loans/interest-chart': {
      id: '/_authenticated/loans/interest-chart'
      path: '/loans/interest-chart'
      fullPath: '/loans/interest-chart'
      preLoaderRoute: typeof AuthenticatedLoansInterestChartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loans/advances': {
      id: '/_authenticated/loans/advances'
      path: '/loans/advances'
      fullPath: '/loans/advances'
      preLoaderRoute: typeof AuthenticatedLoansAdvancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/takpatti': {
      id: '/_authenticated/inventory/takpatti'
      path: '/inventory/takpatti'
      fullPath: '/inventory/takpatti'
      preLoaderRoute: typeof AuthenticatedInventoryTakpattiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/stock-transfer': {
      id: '/_authenticated/inventory/stock-transfer'
      path: '/inventory/stock-transfer'
      fullPath: '/inventory/stock-transfer'
      preLoaderRoute: typeof AuthenticatedInventoryStockTransferRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/nikasi': {
      id: '/_authenticated/inventory/nikasi'
      path: '/inventory/nikasi'
      fullPath: '/inventory/nikasi'
      preLoaderRoute: typeof AuthenticatedInventoryNikasiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/amad': {
      id: '/_authenticated/inventory/amad'
      path: '/inventory/amad'
      fullPath: '/inventory/amad'
      preLoaderRoute: typeof AuthenticatedInventoryAmadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/rent-bills': {
      id: '/_authenticated/billing/rent-bills'
      path: '/billing/rent-bills'
      fullPath: '/billing/rent-bills'
      preLoaderRoute: typeof AuthenticatedBillingRentBillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/receipts': {
      id: '/_authenticated/billing/receipts'
      path: '/billing/receipts'
      fullPath: '/billing/receipts'
      preLoaderRoute: typeof AuthenticatedBillingReceiptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/new-bill': {
      id: '/_authenticated/billing/new-bill'
      path: '/billing/new-bill'
      fullPath: '/billing/new-bill'
      preLoaderRoute: typeof AuthenticatedBillingNewBillRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/$billId': {
      id: '/_authenticated/billing/$billId'
      path: '/billing/$billId'
      fullPath: '/billing/$billId'
      preLoaderRoute: typeof AuthenticatedBillingBillIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bardana/types': {
      id: '/_authenticated/bardana/types'
      path: '/bardana/types'
      fullPath: '/bardana/types'
      preLoaderRoute: typeof AuthenticatedBardanaTypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bardana/receipts': {
      id: '/_authenticated/bardana/receipts'
      path: '/bardana/receipts'
      fullPath: '/bardana/receipts'
      preLoaderRoute: typeof AuthenticatedBardanaReceiptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bardana/outstanding': {
      id: '/_authenticated/bardana/outstanding'
      path: '/bardana/outstanding'
      fullPath: '/bardana/outstanding'
      preLoaderRoute: typeof AuthenticatedBardanaOutstandingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bardana/issues': {
      id: '/_authenticated/bardana/issues'
      path: '/bardana/issues'
      fullPath: '/bardana/issues'
      preLoaderRoute: typeof AuthenticatedBardanaIssuesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/vouchers': {
      id: '/_authenticated/accounts/vouchers'
      path: '/accounts/vouchers'
      fullPath: '/accounts/vouchers'
      preLoaderRoute: typeof AuthenticatedAccountsVouchersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/party-ledger': {
      id: '/_authenticated/accounts/party-ledger'
      path: '/accounts/party-ledger'
      fullPath: '/accounts/party-ledger'
      preLoaderRoute: typeof AuthenticatedAccountsPartyLedgerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/interest': {
      id: '/_authenticated/accounts/interest'
      path: '/accounts/interest'
      fullPath: '/accounts/interest'
      preLoaderRoute: typeof AuthenticatedAccountsInterestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/daybook': {
      id: '/_authenticated/accounts/daybook'
      path: '/accounts/daybook'
      fullPath: '/accounts/daybook'
      preLoaderRoute: typeof AuthenticatedAccountsDaybookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/chart-of-accounts': {
      id: '/_authenticated/accounts/chart-of-accounts'
      path: '/accounts/chart-of-accounts'
      fullPath: '/accounts/chart-of-accounts'
      preLoaderRoute: typeof AuthenticatedAccountsChartOfAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/amad/$amadId': {
      id: '/_authenticated/inventory/amad/$amadId'
      path: '/$amadId'
      fullPath: '/inventory/amad/$amadId'
      preLoaderRoute: typeof AuthenticatedInventoryAmadAmadIdRouteImport
      parentRoute: typeof AuthenticatedInventoryAmadRoute
    }
  }
}

interface AuthenticatedInventoryAmadRouteChildren {
  AuthenticatedInventoryAmadAmadIdRoute: typeof AuthenticatedInventoryAmadAmadIdRoute
}

const AuthenticatedInventoryAmadRouteChildren: AuthenticatedInventoryAmadRouteChildren =
  {
    AuthenticatedInventoryAmadAmadIdRoute:
      AuthenticatedInventoryAmadAmadIdRoute,
  }

const AuthenticatedInventoryAmadRouteWithChildren =
  AuthenticatedInventoryAmadRoute._addFileChildren(
    AuthenticatedInventoryAmadRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMastersRoute: typeof AuthenticatedMastersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAccountsChartOfAccountsRoute: typeof AuthenticatedAccountsChartOfAccountsRoute
  AuthenticatedAccountsDaybookRoute: typeof AuthenticatedAccountsDaybookRoute
  AuthenticatedAccountsInterestRoute: typeof AuthenticatedAccountsInterestRoute
  AuthenticatedAccountsPartyLedgerRoute: typeof AuthenticatedAccountsPartyLedgerRoute
  AuthenticatedAccountsVouchersRoute: typeof AuthenticatedAccountsVouchersRoute
  AuthenticatedBardanaIssuesRoute: typeof AuthenticatedBardanaIssuesRoute
  AuthenticatedBardanaOutstandingRoute: typeof AuthenticatedBardanaOutstandingRoute
  AuthenticatedBardanaReceiptsRoute: typeof AuthenticatedBardanaReceiptsRoute
  AuthenticatedBardanaTypesRoute: typeof AuthenticatedBardanaTypesRoute
  AuthenticatedBillingBillIdRoute: typeof AuthenticatedBillingBillIdRoute
  AuthenticatedBillingNewBillRoute: typeof AuthenticatedBillingNewBillRoute
  AuthenticatedBillingReceiptsRoute: typeof AuthenticatedBillingReceiptsRoute
  AuthenticatedBillingRentBillsRoute: typeof AuthenticatedBillingRentBillsRoute
  AuthenticatedInventoryAmadRoute: typeof AuthenticatedInventoryAmadRouteWithChildren
  AuthenticatedInventoryNikasiRoute: typeof AuthenticatedInventoryNikasiRoute
  AuthenticatedInventoryStockTransferRoute: typeof AuthenticatedInventoryStockTransferRoute
  AuthenticatedInventoryTakpattiRoute: typeof AuthenticatedInventoryTakpattiRoute
  AuthenticatedLoansAdvancesRoute: typeof AuthenticatedLoansAdvancesRoute
  AuthenticatedLoansInterestChartRoute: typeof AuthenticatedLoansInterestChartRoute
  AuthenticatedLoansLedgerRoute: typeof AuthenticatedLoansLedgerRoute
  AuthenticatedLoansLoansRoute: typeof AuthenticatedLoansLoansRoute
  AuthenticatedPayrollAttendanceRoute: typeof AuthenticatedPayrollAttendanceRoute
  AuthenticatedPayrollDailyWagesRoute: typeof AuthenticatedPayrollDailyWagesRoute
  AuthenticatedPayrollEmployeesRoute: typeof AuthenticatedPayrollEmployeesRoute
  AuthenticatedPayrollLoansRoute: typeof AuthenticatedPayrollLoansRoute
  AuthenticatedPayrollMastersRoute: typeof AuthenticatedPayrollMastersRoute
  AuthenticatedPayrollPayslipRoute: typeof AuthenticatedPayrollPayslipRoute
  AuthenticatedPayrollSalaryRoute: typeof AuthenticatedPayrollSalaryRoute
  AuthenticatedTradingGatePassRoute: typeof AuthenticatedTradingGatePassRoute
  AuthenticatedTradingKataiRoute: typeof AuthenticatedTradingKataiRoute
  AuthenticatedTradingSaudaRoute: typeof AuthenticatedTradingSaudaRoute
  AuthenticatedWarehouseChambersRoute: typeof AuthenticatedWarehouseChambersRoute
  AuthenticatedWarehouseLoadingRoute: typeof AuthenticatedWarehouseLoadingRoute
  AuthenticatedWarehouseMeterReadingRoute: typeof AuthenticatedWarehouseMeterReadingRoute
  AuthenticatedWarehouseRoomMapRoute: typeof AuthenticatedWarehouseRoomMapRoute
  AuthenticatedWarehouseShiftingRoute: typeof AuthenticatedWarehouseShiftingRoute
  AuthenticatedWarehouseTemperatureRoute: typeof AuthenticatedWarehouseTemperatureRoute
  AuthenticatedWarehouseUnloadingRoute: typeof AuthenticatedWarehouseUnloadingRoute
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
  AuthenticatedBardanaIndexRoute: typeof AuthenticatedBardanaIndexRoute
  AuthenticatedBillingIndexRoute: typeof AuthenticatedBillingIndexRoute
  AuthenticatedLoansIndexRoute: typeof AuthenticatedLoansIndexRoute
  AuthenticatedPayrollIndexRoute: typeof AuthenticatedPayrollIndexRoute
  AuthenticatedTradingIndexRoute: typeof AuthenticatedTradingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMastersRoute: AuthenticatedMastersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAccountsChartOfAccountsRoute:
    AuthenticatedAccountsChartOfAccountsRoute,
  AuthenticatedAccountsDaybookRoute: AuthenticatedAccountsDaybookRoute,
  AuthenticatedAccountsInterestRoute: AuthenticatedAccountsInterestRoute,
  AuthenticatedAccountsPartyLedgerRoute: AuthenticatedAccountsPartyLedgerRoute,
  AuthenticatedAccountsVouchersRoute: AuthenticatedAccountsVouchersRoute,
  AuthenticatedBardanaIssuesRoute: AuthenticatedBardanaIssuesRoute,
  AuthenticatedBardanaOutstandingRoute: AuthenticatedBardanaOutstandingRoute,
  AuthenticatedBardanaReceiptsRoute: AuthenticatedBardanaReceiptsRoute,
  AuthenticatedBardanaTypesRoute: AuthenticatedBardanaTypesRoute,
  AuthenticatedBillingBillIdRoute: AuthenticatedBillingBillIdRoute,
  AuthenticatedBillingNewBillRoute: AuthenticatedBillingNewBillRoute,
  AuthenticatedBillingReceiptsRoute: AuthenticatedBillingReceiptsRoute,
  AuthenticatedBillingRentBillsRoute: AuthenticatedBillingRentBillsRoute,
  AuthenticatedInventoryAmadRoute: AuthenticatedInventoryAmadRouteWithChildren,
  AuthenticatedInventoryNikasiRoute: AuthenticatedInventoryNikasiRoute,
  AuthenticatedInventoryStockTransferRoute:
    AuthenticatedInventoryStockTransferRoute,
  AuthenticatedInventoryTakpattiRoute: AuthenticatedInventoryTakpattiRoute,
  AuthenticatedLoansAdvancesRoute: AuthenticatedLoansAdvancesRoute,
  AuthenticatedLoansInterestChartRoute: AuthenticatedLoansInterestChartRoute,
  AuthenticatedLoansLedgerRoute: AuthenticatedLoansLedgerRoute,
  AuthenticatedLoansLoansRoute: AuthenticatedLoansLoansRoute,
  AuthenticatedPayrollAttendanceRoute: AuthenticatedPayrollAttendanceRoute,
  AuthenticatedPayrollDailyWagesRoute: AuthenticatedPayrollDailyWagesRoute,
  AuthenticatedPayrollEmployeesRoute: AuthenticatedPayrollEmployeesRoute,
  AuthenticatedPayrollLoansRoute: AuthenticatedPayrollLoansRoute,
  AuthenticatedPayrollMastersRoute: AuthenticatedPayrollMastersRoute,
  AuthenticatedPayrollPayslipRoute: AuthenticatedPayrollPayslipRoute,
  AuthenticatedPayrollSalaryRoute: AuthenticatedPayrollSalaryRoute,
  AuthenticatedTradingGatePassRoute: AuthenticatedTradingGatePassRoute,
  AuthenticatedTradingKataiRoute: AuthenticatedTradingKataiRoute,
  AuthenticatedTradingSaudaRoute: AuthenticatedTradingSaudaRoute,
  AuthenticatedWarehouseChambersRoute: AuthenticatedWarehouseChambersRoute,
  AuthenticatedWarehouseLoadingRoute: AuthenticatedWarehouseLoadingRoute,
  AuthenticatedWarehouseMeterReadingRoute:
    AuthenticatedWarehouseMeterReadingRoute,
  AuthenticatedWarehouseRoomMapRoute: AuthenticatedWarehouseRoomMapRoute,
  AuthenticatedWarehouseShiftingRoute: AuthenticatedWarehouseShiftingRoute,
  AuthenticatedWarehouseTemperatureRoute:
    AuthenticatedWarehouseTemperatureRoute,
  AuthenticatedWarehouseUnloadingRoute: AuthenticatedWarehouseUnloadingRoute,
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
  AuthenticatedBardanaIndexRoute: AuthenticatedBardanaIndexRoute,
  AuthenticatedBillingIndexRoute: AuthenticatedBillingIndexRoute,
  AuthenticatedLoansIndexRoute: AuthenticatedLoansIndexRoute,
  AuthenticatedPayrollIndexRoute: AuthenticatedPayrollIndexRoute,
  AuthenticatedTradingIndexRoute: AuthenticatedTradingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConfirmSignupRoute: ConfirmSignupRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
