/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfirmSignupRouteImport } from './routes/confirm-signup'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMastersRouteImport } from './routes/_authenticated/masters'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChambersRouteImport } from './routes/_authenticated/chambers'
import { Route as AuthenticatedBardanaIndexRouteImport } from './routes/_authenticated/bardana/index'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts/index'
import { Route as AuthenticatedInventoryTakpattiRouteImport } from './routes/_authenticated/inventory/takpatti'
import { Route as AuthenticatedInventoryStockTransferRouteImport } from './routes/_authenticated/inventory/stock-transfer'
import { Route as AuthenticatedInventoryNikasiRouteImport } from './routes/_authenticated/inventory/nikasi'
import { Route as AuthenticatedInventoryAmadRouteImport } from './routes/_authenticated/inventory/amad'
import { Route as AuthenticatedBardanaTypesRouteImport } from './routes/_authenticated/bardana/types'
import { Route as AuthenticatedBardanaReceiptsRouteImport } from './routes/_authenticated/bardana/receipts'
import { Route as AuthenticatedBardanaOutstandingRouteImport } from './routes/_authenticated/bardana/outstanding'
import { Route as AuthenticatedBardanaIssuesRouteImport } from './routes/_authenticated/bardana/issues'
import { Route as AuthenticatedAccountsVouchersRouteImport } from './routes/_authenticated/accounts/vouchers'
import { Route as AuthenticatedAccountsPartyLedgerRouteImport } from './routes/_authenticated/accounts/party-ledger'
import { Route as AuthenticatedAccountsInterestRouteImport } from './routes/_authenticated/accounts/interest'
import { Route as AuthenticatedAccountsDaybookRouteImport } from './routes/_authenticated/accounts/daybook'
import { Route as AuthenticatedAccountsChartOfAccountsRouteImport } from './routes/_authenticated/accounts/chart-of-accounts'
import { Route as AuthenticatedInventoryAmadAmadIdRouteImport } from './routes/_authenticated/inventory/amad.$amadId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmSignupRoute = ConfirmSignupRouteImport.update({
  id: '/confirm-signup',
  path: '/confirm-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMastersRoute = AuthenticatedMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChambersRoute = AuthenticatedChambersRouteImport.update({
  id: '/chambers',
  path: '/chambers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBardanaIndexRoute =
  AuthenticatedBardanaIndexRouteImport.update({
    id: '/bardana/',
    path: '/bardana/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryTakpattiRoute =
  AuthenticatedInventoryTakpattiRouteImport.update({
    id: '/inventory/takpatti',
    path: '/inventory/takpatti',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryStockTransferRoute =
  AuthenticatedInventoryStockTransferRouteImport.update({
    id: '/inventory/stock-transfer',
    path: '/inventory/stock-transfer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryNikasiRoute =
  AuthenticatedInventoryNikasiRouteImport.update({
    id: '/inventory/nikasi',
    path: '/inventory/nikasi',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryAmadRoute =
  AuthenticatedInventoryAmadRouteImport.update({
    id: '/inventory/amad',
    path: '/inventory/amad',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBardanaTypesRoute =
  AuthenticatedBardanaTypesRouteImport.update({
    id: '/bardana/types',
    path: '/bardana/types',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBardanaReceiptsRoute =
  AuthenticatedBardanaReceiptsRouteImport.update({
    id: '/bardana/receipts',
    path: '/bardana/receipts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBardanaOutstandingRoute =
  AuthenticatedBardanaOutstandingRouteImport.update({
    id: '/bardana/outstanding',
    path: '/bardana/outstanding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBardanaIssuesRoute =
  AuthenticatedBardanaIssuesRouteImport.update({
    id: '/bardana/issues',
    path: '/bardana/issues',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsVouchersRoute =
  AuthenticatedAccountsVouchersRouteImport.update({
    id: '/accounts/vouchers',
    path: '/accounts/vouchers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsPartyLedgerRoute =
  AuthenticatedAccountsPartyLedgerRouteImport.update({
    id: '/accounts/party-ledger',
    path: '/accounts/party-ledger',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsInterestRoute =
  AuthenticatedAccountsInterestRouteImport.update({
    id: '/accounts/interest',
    path: '/accounts/interest',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsDaybookRoute =
  AuthenticatedAccountsDaybookRouteImport.update({
    id: '/accounts/daybook',
    path: '/accounts/daybook',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsChartOfAccountsRoute =
  AuthenticatedAccountsChartOfAccountsRouteImport.update({
    id: '/accounts/chart-of-accounts',
    path: '/accounts/chart-of-accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryAmadAmadIdRoute =
  AuthenticatedInventoryAmadAmadIdRouteImport.update({
    id: '/$amadId',
    path: '/$amadId',
    getParentRoute: () => AuthenticatedInventoryAmadRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm-signup': typeof ConfirmSignupRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chambers': typeof AuthenticatedChambersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/masters': typeof AuthenticatedMastersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/accounts/chart-of-accounts': typeof AuthenticatedAccountsChartOfAccountsRoute
  '/accounts/daybook': typeof AuthenticatedAccountsDaybookRoute
  '/accounts/interest': typeof AuthenticatedAccountsInterestRoute
  '/accounts/party-ledger': typeof AuthenticatedAccountsPartyLedgerRoute
  '/accounts/vouchers': typeof AuthenticatedAccountsVouchersRoute
  '/bardana/issues': typeof AuthenticatedBardanaIssuesRoute
  '/bardana/outstanding': typeof AuthenticatedBardanaOutstandingRoute
  '/bardana/receipts': typeof AuthenticatedBardanaReceiptsRoute
  '/bardana/types': typeof AuthenticatedBardanaTypesRoute
  '/inventory/amad': typeof AuthenticatedInventoryAmadRouteWithChildren
  '/inventory/nikasi': typeof AuthenticatedInventoryNikasiRoute
  '/inventory/stock-transfer': typeof AuthenticatedInventoryStockTransferRoute
  '/inventory/takpatti': typeof AuthenticatedInventoryTakpattiRoute
  '/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/bardana/': typeof AuthenticatedBardanaIndexRoute
  '/inventory/amad/$amadId': typeof AuthenticatedInventoryAmadAmadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-signup': typeof ConfirmSignupRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chambers': typeof AuthenticatedChambersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/masters': typeof AuthenticatedMastersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/accounts/chart-of-accounts': typeof AuthenticatedAccountsChartOfAccountsRoute
  '/accounts/daybook': typeof AuthenticatedAccountsDaybookRoute
  '/accounts/interest': typeof AuthenticatedAccountsInterestRoute
  '/accounts/party-ledger': typeof AuthenticatedAccountsPartyLedgerRoute
  '/accounts/vouchers': typeof AuthenticatedAccountsVouchersRoute
  '/bardana/issues': typeof AuthenticatedBardanaIssuesRoute
  '/bardana/outstanding': typeof AuthenticatedBardanaOutstandingRoute
  '/bardana/receipts': typeof AuthenticatedBardanaReceiptsRoute
  '/bardana/types': typeof AuthenticatedBardanaTypesRoute
  '/inventory/amad': typeof AuthenticatedInventoryAmadRouteWithChildren
  '/inventory/nikasi': typeof AuthenticatedInventoryNikasiRoute
  '/inventory/stock-transfer': typeof AuthenticatedInventoryStockTransferRoute
  '/inventory/takpatti': typeof AuthenticatedInventoryTakpattiRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
  '/bardana': typeof AuthenticatedBardanaIndexRoute
  '/inventory/amad/$amadId': typeof AuthenticatedInventoryAmadAmadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/confirm-signup': typeof ConfirmSignupRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/chambers': typeof AuthenticatedChambersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/masters': typeof AuthenticatedMastersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/accounts/chart-of-accounts': typeof AuthenticatedAccountsChartOfAccountsRoute
  '/_authenticated/accounts/daybook': typeof AuthenticatedAccountsDaybookRoute
  '/_authenticated/accounts/interest': typeof AuthenticatedAccountsInterestRoute
  '/_authenticated/accounts/party-ledger': typeof AuthenticatedAccountsPartyLedgerRoute
  '/_authenticated/accounts/vouchers': typeof AuthenticatedAccountsVouchersRoute
  '/_authenticated/bardana/issues': typeof AuthenticatedBardanaIssuesRoute
  '/_authenticated/bardana/outstanding': typeof AuthenticatedBardanaOutstandingRoute
  '/_authenticated/bardana/receipts': typeof AuthenticatedBardanaReceiptsRoute
  '/_authenticated/bardana/types': typeof AuthenticatedBardanaTypesRoute
  '/_authenticated/inventory/amad': typeof AuthenticatedInventoryAmadRouteWithChildren
  '/_authenticated/inventory/nikasi': typeof AuthenticatedInventoryNikasiRoute
  '/_authenticated/inventory/stock-transfer': typeof AuthenticatedInventoryStockTransferRoute
  '/_authenticated/inventory/takpatti': typeof AuthenticatedInventoryTakpattiRoute
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/_authenticated/bardana/': typeof AuthenticatedBardanaIndexRoute
  '/_authenticated/inventory/amad/$amadId': typeof AuthenticatedInventoryAmadAmadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-signup'
    | '/login'
    | '/signup'
    | '/chambers'
    | '/dashboard'
    | '/masters'
    | '/settings'
    | '/accounts/chart-of-accounts'
    | '/accounts/daybook'
    | '/accounts/interest'
    | '/accounts/party-ledger'
    | '/accounts/vouchers'
    | '/bardana/issues'
    | '/bardana/outstanding'
    | '/bardana/receipts'
    | '/bardana/types'
    | '/inventory/amad'
    | '/inventory/nikasi'
    | '/inventory/stock-transfer'
    | '/inventory/takpatti'
    | '/accounts/'
    | '/bardana/'
    | '/inventory/amad/$amadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-signup'
    | '/login'
    | '/signup'
    | '/chambers'
    | '/dashboard'
    | '/masters'
    | '/settings'
    | '/accounts/chart-of-accounts'
    | '/accounts/daybook'
    | '/accounts/interest'
    | '/accounts/party-ledger'
    | '/accounts/vouchers'
    | '/bardana/issues'
    | '/bardana/outstanding'
    | '/bardana/receipts'
    | '/bardana/types'
    | '/inventory/amad'
    | '/inventory/nikasi'
    | '/inventory/stock-transfer'
    | '/inventory/takpatti'
    | '/accounts'
    | '/bardana'
    | '/inventory/amad/$amadId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/confirm-signup'
    | '/login'
    | '/signup'
    | '/_authenticated/chambers'
    | '/_authenticated/dashboard'
    | '/_authenticated/masters'
    | '/_authenticated/settings'
    | '/_authenticated/accounts/chart-of-accounts'
    | '/_authenticated/accounts/daybook'
    | '/_authenticated/accounts/interest'
    | '/_authenticated/accounts/party-ledger'
    | '/_authenticated/accounts/vouchers'
    | '/_authenticated/bardana/issues'
    | '/_authenticated/bardana/outstanding'
    | '/_authenticated/bardana/receipts'
    | '/_authenticated/bardana/types'
    | '/_authenticated/inventory/amad'
    | '/_authenticated/inventory/nikasi'
    | '/_authenticated/inventory/stock-transfer'
    | '/_authenticated/inventory/takpatti'
    | '/_authenticated/accounts/'
    | '/_authenticated/bardana/'
    | '/_authenticated/inventory/amad/$amadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConfirmSignupRoute: typeof ConfirmSignupRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-signup': {
      id: '/confirm-signup'
      path: '/confirm-signup'
      fullPath: '/confirm-signup'
      preLoaderRoute: typeof ConfirmSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters': {
      id: '/_authenticated/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof AuthenticatedMastersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chambers': {
      id: '/_authenticated/chambers'
      path: '/chambers'
      fullPath: '/chambers'
      preLoaderRoute: typeof AuthenticatedChambersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bardana/': {
      id: '/_authenticated/bardana/'
      path: '/bardana'
      fullPath: '/bardana/'
      preLoaderRoute: typeof AuthenticatedBardanaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/takpatti': {
      id: '/_authenticated/inventory/takpatti'
      path: '/inventory/takpatti'
      fullPath: '/inventory/takpatti'
      preLoaderRoute: typeof AuthenticatedInventoryTakpattiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/stock-transfer': {
      id: '/_authenticated/inventory/stock-transfer'
      path: '/inventory/stock-transfer'
      fullPath: '/inventory/stock-transfer'
      preLoaderRoute: typeof AuthenticatedInventoryStockTransferRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/nikasi': {
      id: '/_authenticated/inventory/nikasi'
      path: '/inventory/nikasi'
      fullPath: '/inventory/nikasi'
      preLoaderRoute: typeof AuthenticatedInventoryNikasiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/amad': {
      id: '/_authenticated/inventory/amad'
      path: '/inventory/amad'
      fullPath: '/inventory/amad'
      preLoaderRoute: typeof AuthenticatedInventoryAmadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bardana/types': {
      id: '/_authenticated/bardana/types'
      path: '/bardana/types'
      fullPath: '/bardana/types'
      preLoaderRoute: typeof AuthenticatedBardanaTypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bardana/receipts': {
      id: '/_authenticated/bardana/receipts'
      path: '/bardana/receipts'
      fullPath: '/bardana/receipts'
      preLoaderRoute: typeof AuthenticatedBardanaReceiptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bardana/outstanding': {
      id: '/_authenticated/bardana/outstanding'
      path: '/bardana/outstanding'
      fullPath: '/bardana/outstanding'
      preLoaderRoute: typeof AuthenticatedBardanaOutstandingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bardana/issues': {
      id: '/_authenticated/bardana/issues'
      path: '/bardana/issues'
      fullPath: '/bardana/issues'
      preLoaderRoute: typeof AuthenticatedBardanaIssuesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/vouchers': {
      id: '/_authenticated/accounts/vouchers'
      path: '/accounts/vouchers'
      fullPath: '/accounts/vouchers'
      preLoaderRoute: typeof AuthenticatedAccountsVouchersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/party-ledger': {
      id: '/_authenticated/accounts/party-ledger'
      path: '/accounts/party-ledger'
      fullPath: '/accounts/party-ledger'
      preLoaderRoute: typeof AuthenticatedAccountsPartyLedgerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/interest': {
      id: '/_authenticated/accounts/interest'
      path: '/accounts/interest'
      fullPath: '/accounts/interest'
      preLoaderRoute: typeof AuthenticatedAccountsInterestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/daybook': {
      id: '/_authenticated/accounts/daybook'
      path: '/accounts/daybook'
      fullPath: '/accounts/daybook'
      preLoaderRoute: typeof AuthenticatedAccountsDaybookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/chart-of-accounts': {
      id: '/_authenticated/accounts/chart-of-accounts'
      path: '/accounts/chart-of-accounts'
      fullPath: '/accounts/chart-of-accounts'
      preLoaderRoute: typeof AuthenticatedAccountsChartOfAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/amad/$amadId': {
      id: '/_authenticated/inventory/amad/$amadId'
      path: '/$amadId'
      fullPath: '/inventory/amad/$amadId'
      preLoaderRoute: typeof AuthenticatedInventoryAmadAmadIdRouteImport
      parentRoute: typeof AuthenticatedInventoryAmadRoute
    }
  }
}

interface AuthenticatedInventoryAmadRouteChildren {
  AuthenticatedInventoryAmadAmadIdRoute: typeof AuthenticatedInventoryAmadAmadIdRoute
}

const AuthenticatedInventoryAmadRouteChildren: AuthenticatedInventoryAmadRouteChildren =
  {
    AuthenticatedInventoryAmadAmadIdRoute:
      AuthenticatedInventoryAmadAmadIdRoute,
  }

const AuthenticatedInventoryAmadRouteWithChildren =
  AuthenticatedInventoryAmadRoute._addFileChildren(
    AuthenticatedInventoryAmadRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedChambersRoute: typeof AuthenticatedChambersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMastersRoute: typeof AuthenticatedMastersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAccountsChartOfAccountsRoute: typeof AuthenticatedAccountsChartOfAccountsRoute
  AuthenticatedAccountsDaybookRoute: typeof AuthenticatedAccountsDaybookRoute
  AuthenticatedAccountsInterestRoute: typeof AuthenticatedAccountsInterestRoute
  AuthenticatedAccountsPartyLedgerRoute: typeof AuthenticatedAccountsPartyLedgerRoute
  AuthenticatedAccountsVouchersRoute: typeof AuthenticatedAccountsVouchersRoute
  AuthenticatedBardanaIssuesRoute: typeof AuthenticatedBardanaIssuesRoute
  AuthenticatedBardanaOutstandingRoute: typeof AuthenticatedBardanaOutstandingRoute
  AuthenticatedBardanaReceiptsRoute: typeof AuthenticatedBardanaReceiptsRoute
  AuthenticatedBardanaTypesRoute: typeof AuthenticatedBardanaTypesRoute
  AuthenticatedInventoryAmadRoute: typeof AuthenticatedInventoryAmadRouteWithChildren
  AuthenticatedInventoryNikasiRoute: typeof AuthenticatedInventoryNikasiRoute
  AuthenticatedInventoryStockTransferRoute: typeof AuthenticatedInventoryStockTransferRoute
  AuthenticatedInventoryTakpattiRoute: typeof AuthenticatedInventoryTakpattiRoute
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
  AuthenticatedBardanaIndexRoute: typeof AuthenticatedBardanaIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChambersRoute: AuthenticatedChambersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMastersRoute: AuthenticatedMastersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAccountsChartOfAccountsRoute:
    AuthenticatedAccountsChartOfAccountsRoute,
  AuthenticatedAccountsDaybookRoute: AuthenticatedAccountsDaybookRoute,
  AuthenticatedAccountsInterestRoute: AuthenticatedAccountsInterestRoute,
  AuthenticatedAccountsPartyLedgerRoute: AuthenticatedAccountsPartyLedgerRoute,
  AuthenticatedAccountsVouchersRoute: AuthenticatedAccountsVouchersRoute,
  AuthenticatedBardanaIssuesRoute: AuthenticatedBardanaIssuesRoute,
  AuthenticatedBardanaOutstandingRoute: AuthenticatedBardanaOutstandingRoute,
  AuthenticatedBardanaReceiptsRoute: AuthenticatedBardanaReceiptsRoute,
  AuthenticatedBardanaTypesRoute: AuthenticatedBardanaTypesRoute,
  AuthenticatedInventoryAmadRoute: AuthenticatedInventoryAmadRouteWithChildren,
  AuthenticatedInventoryNikasiRoute: AuthenticatedInventoryNikasiRoute,
  AuthenticatedInventoryStockTransferRoute:
    AuthenticatedInventoryStockTransferRoute,
  AuthenticatedInventoryTakpattiRoute: AuthenticatedInventoryTakpattiRoute,
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
  AuthenticatedBardanaIndexRoute: AuthenticatedBardanaIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConfirmSignupRoute: ConfirmSignupRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
