/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfirmSignupRouteImport } from './routes/confirm-signup'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMastersRouteImport } from './routes/_authenticated/masters'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInventoryTakpattiRouteImport } from './routes/_authenticated/inventory/takpatti'
import { Route as AuthenticatedInventoryStockTransferRouteImport } from './routes/_authenticated/inventory/stock-transfer'
import { Route as AuthenticatedInventoryNikasiRouteImport } from './routes/_authenticated/inventory/nikasi'
import { Route as AuthenticatedInventoryAmadRouteImport } from './routes/_authenticated/inventory/amad'
import { Route as AuthenticatedInventoryAmadAmadIdRouteImport } from './routes/_authenticated/inventory/amad.$amadId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmSignupRoute = ConfirmSignupRouteImport.update({
  id: '/confirm-signup',
  path: '/confirm-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMastersRoute = AuthenticatedMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryTakpattiRoute =
  AuthenticatedInventoryTakpattiRouteImport.update({
    id: '/inventory/takpatti',
    path: '/inventory/takpatti',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryStockTransferRoute =
  AuthenticatedInventoryStockTransferRouteImport.update({
    id: '/inventory/stock-transfer',
    path: '/inventory/stock-transfer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryNikasiRoute =
  AuthenticatedInventoryNikasiRouteImport.update({
    id: '/inventory/nikasi',
    path: '/inventory/nikasi',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryAmadRoute =
  AuthenticatedInventoryAmadRouteImport.update({
    id: '/inventory/amad',
    path: '/inventory/amad',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryAmadAmadIdRoute =
  AuthenticatedInventoryAmadAmadIdRouteImport.update({
    id: '/$amadId',
    path: '/$amadId',
    getParentRoute: () => AuthenticatedInventoryAmadRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm-signup': typeof ConfirmSignupRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/masters': typeof AuthenticatedMastersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/inventory/amad': typeof AuthenticatedInventoryAmadRouteWithChildren
  '/inventory/nikasi': typeof AuthenticatedInventoryNikasiRoute
  '/inventory/stock-transfer': typeof AuthenticatedInventoryStockTransferRoute
  '/inventory/takpatti': typeof AuthenticatedInventoryTakpattiRoute
  '/inventory/amad/$amadId': typeof AuthenticatedInventoryAmadAmadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-signup': typeof ConfirmSignupRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/masters': typeof AuthenticatedMastersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/inventory/amad': typeof AuthenticatedInventoryAmadRouteWithChildren
  '/inventory/nikasi': typeof AuthenticatedInventoryNikasiRoute
  '/inventory/stock-transfer': typeof AuthenticatedInventoryStockTransferRoute
  '/inventory/takpatti': typeof AuthenticatedInventoryTakpattiRoute
  '/inventory/amad/$amadId': typeof AuthenticatedInventoryAmadAmadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/confirm-signup': typeof ConfirmSignupRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/masters': typeof AuthenticatedMastersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/inventory/amad': typeof AuthenticatedInventoryAmadRouteWithChildren
  '/_authenticated/inventory/nikasi': typeof AuthenticatedInventoryNikasiRoute
  '/_authenticated/inventory/stock-transfer': typeof AuthenticatedInventoryStockTransferRoute
  '/_authenticated/inventory/takpatti': typeof AuthenticatedInventoryTakpattiRoute
  '/_authenticated/inventory/amad/$amadId': typeof AuthenticatedInventoryAmadAmadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-signup'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/masters'
    | '/settings'
    | '/inventory/amad'
    | '/inventory/nikasi'
    | '/inventory/stock-transfer'
    | '/inventory/takpatti'
    | '/inventory/amad/$amadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-signup'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/masters'
    | '/settings'
    | '/inventory/amad'
    | '/inventory/nikasi'
    | '/inventory/stock-transfer'
    | '/inventory/takpatti'
    | '/inventory/amad/$amadId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/confirm-signup'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/masters'
    | '/_authenticated/settings'
    | '/_authenticated/inventory/amad'
    | '/_authenticated/inventory/nikasi'
    | '/_authenticated/inventory/stock-transfer'
    | '/_authenticated/inventory/takpatti'
    | '/_authenticated/inventory/amad/$amadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConfirmSignupRoute: typeof ConfirmSignupRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-signup': {
      id: '/confirm-signup'
      path: '/confirm-signup'
      fullPath: '/confirm-signup'
      preLoaderRoute: typeof ConfirmSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters': {
      id: '/_authenticated/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof AuthenticatedMastersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/takpatti': {
      id: '/_authenticated/inventory/takpatti'
      path: '/inventory/takpatti'
      fullPath: '/inventory/takpatti'
      preLoaderRoute: typeof AuthenticatedInventoryTakpattiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/stock-transfer': {
      id: '/_authenticated/inventory/stock-transfer'
      path: '/inventory/stock-transfer'
      fullPath: '/inventory/stock-transfer'
      preLoaderRoute: typeof AuthenticatedInventoryStockTransferRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/nikasi': {
      id: '/_authenticated/inventory/nikasi'
      path: '/inventory/nikasi'
      fullPath: '/inventory/nikasi'
      preLoaderRoute: typeof AuthenticatedInventoryNikasiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/amad': {
      id: '/_authenticated/inventory/amad'
      path: '/inventory/amad'
      fullPath: '/inventory/amad'
      preLoaderRoute: typeof AuthenticatedInventoryAmadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/amad/$amadId': {
      id: '/_authenticated/inventory/amad/$amadId'
      path: '/$amadId'
      fullPath: '/inventory/amad/$amadId'
      preLoaderRoute: typeof AuthenticatedInventoryAmadAmadIdRouteImport
      parentRoute: typeof AuthenticatedInventoryAmadRoute
    }
  }
}

interface AuthenticatedInventoryAmadRouteChildren {
  AuthenticatedInventoryAmadAmadIdRoute: typeof AuthenticatedInventoryAmadAmadIdRoute
}

const AuthenticatedInventoryAmadRouteChildren: AuthenticatedInventoryAmadRouteChildren =
  {
    AuthenticatedInventoryAmadAmadIdRoute:
      AuthenticatedInventoryAmadAmadIdRoute,
  }

const AuthenticatedInventoryAmadRouteWithChildren =
  AuthenticatedInventoryAmadRoute._addFileChildren(
    AuthenticatedInventoryAmadRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMastersRoute: typeof AuthenticatedMastersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedInventoryAmadRoute: typeof AuthenticatedInventoryAmadRouteWithChildren
  AuthenticatedInventoryNikasiRoute: typeof AuthenticatedInventoryNikasiRoute
  AuthenticatedInventoryStockTransferRoute: typeof AuthenticatedInventoryStockTransferRoute
  AuthenticatedInventoryTakpattiRoute: typeof AuthenticatedInventoryTakpattiRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMastersRoute: AuthenticatedMastersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedInventoryAmadRoute: AuthenticatedInventoryAmadRouteWithChildren,
  AuthenticatedInventoryNikasiRoute: AuthenticatedInventoryNikasiRoute,
  AuthenticatedInventoryStockTransferRoute:
    AuthenticatedInventoryStockTransferRoute,
  AuthenticatedInventoryTakpattiRoute: AuthenticatedInventoryTakpattiRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConfirmSignupRoute: ConfirmSignupRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
